version: '3.4'

services:
  app:
      build: ./php
      container_name: app_brk
      ports:
          - "80:80"
          - "443:443"
      networks:
          - backend
          - frontend
      volumes:
          - ../www/:/var/www/
      depends_on:
        - db
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=brk
      - MYSQL_USER=brk
      - MYSQL_PASSWORD=secret
    volumes:
        - ./mysql/data:/var/lib/mysql:rw
    ports:
      - "3386:3306"
    networks:
        - backend
networks:
    backend:
    frontend:

